// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
plugins {
    kotlin("multiplatform")
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("21"))
        }
        compilations.named("main").configure {
            compileTaskProvider.configure {
                compilerOptions {
                    freeCompilerArgs.add("-Xjdk-release=21")
                }
            }
        }
        compilations.named("test").configure {
            compileTaskProvider.configure {
                compilerOptions {
                    jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
                    freeCompilerArgs.add("-Xjdk-release=25")
                }
            }
        }
    }
    linuxX64 {
    }
    jvmToolchain(25)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("jvmMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("jvmTest").apply {
            dependsOn(getByName("commonTest"))
            kotlin.srcDir("test@jvm")
            dependencies {
                implementation(kotlin("test-junit5"))
                implementation("org.junit.jupiter:junit-jupiter:5.14.1")
            }
        }
        maybeCreate("nativeMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("nativeTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("linuxMain").apply {
            dependsOn(getByName("nativeMain"))
        }
        maybeCreate("linuxTest").apply {
            dependsOn(getByName("nativeTest"))
        }
        maybeCreate("linuxX64Main").apply {
            dependsOn(getByName("linuxMain"))
        }
        maybeCreate("linuxX64Test").apply {
            dependsOn(getByName("linuxTest"))
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
