// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
pluginManagement {
    repositories {
        maven {
            name = "mavenCentral"
            url = uri("https://mirror.example/maven")
            val repositoryCredentials0 = java.util.Properties()
            file("credentials.properties").inputStream().use(repositoryCredentials0::load)
            credentials {
                username = repositoryCredentials0.getProperty("mirror.username")
                password = repositoryCredentials0.getProperty("mirror.password")
            }
        }
        gradlePluginPortal()
    }
}

rootProject.name = "repo-credentials"
