// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    kotlin("multiplatform") version "2.4.10"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
            freeCompilerArgs.add("-Xjdk-release=17")
        }
    }
    linuxX64 {
    }
    macosArm64 {
    }
    jvmToolchain(25)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
                implementation("org.example:common:1.0")
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("desktopMain").apply {
            dependsOn(getByName("commonMain"))
            kotlin.srcDir("src@desktop")
            dependencies {
                implementation("org.example:desktop:1.0")
            }
        }
        maybeCreate("desktopTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("nativeMain").apply {
            dependsOn(getByName("commonMain"))
            kotlin.srcDir("src@native")
            dependencies {
                implementation("org.example:native-only:1.0")
            }
        }
        maybeCreate("nativeTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("posixMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("posixTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("appleMain").apply {
            dependsOn(getByName("nativeMain"))
            dependsOn(getByName("posixMain"))
        }
        maybeCreate("appleTest").apply {
            dependsOn(getByName("nativeTest"))
            dependsOn(getByName("posixTest"))
        }
        maybeCreate("jvmMain").apply {
            dependsOn(getByName("desktopMain"))
            kotlin.srcDir("src@jvm")
        }
        maybeCreate("jvmTest").apply {
            dependsOn(getByName("desktopTest"))
            dependencies {
                implementation("org.example:jvm-test:1.0")
            }
        }
        maybeCreate("linuxMain").apply {
            dependsOn(getByName("nativeMain"))
            dependsOn(getByName("desktopMain"))
            dependsOn(getByName("posixMain"))
            resources.srcDir("resources@linux")
        }
        maybeCreate("linuxTest").apply {
            dependsOn(getByName("nativeTest"))
            dependsOn(getByName("desktopTest"))
            dependsOn(getByName("posixTest"))
        }
        maybeCreate("linuxX64Main").apply {
            dependsOn(getByName("linuxMain"))
        }
        maybeCreate("linuxX64Test").apply {
            dependsOn(getByName("linuxTest"))
        }
        maybeCreate("macosMain").apply {
            dependsOn(getByName("appleMain"))
        }
        maybeCreate("macosTest").apply {
            dependsOn(getByName("appleTest"))
        }
        maybeCreate("macosArm64Main").apply {
            dependsOn(getByName("macosMain"))
        }
        maybeCreate("macosArm64Test").apply {
            dependsOn(getByName("macosTest"))
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
