// Generated by ktc-to-gradle 0.13.0. Safe to regenerate.
plugins {
    kotlin("multiplatform")
    id("com.android.kotlin.multiplatform.library")
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    androidLibrary {
        namespace = "example.library._2nd_ui"
        compileSdk = 37
        minSdk = 24
        withHostTestBuilder {}.configure {}
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
            freeCompilerArgs.add("-Xjdk-release=25")
        }
    }
    jvmToolchain(25)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("androidMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("androidHostTest").apply {
            dependsOn(getByName("commonTest"))
            dependencies {
                implementation(kotlin("test-junit5"))
            }
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
