// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    kotlin("jvm") version "2.4.10"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvmToolchain(25)
    compilerOptions {
        this.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
    }
}

java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
}

sourceSets {
    main {
        kotlin.srcDir("src")
        resources.srcDir("resources")
    }
    test {
        kotlin.srcDir("test")
        resources.srcDir("testResources")
    }
}

dependencies {
    testImplementation(kotlin("test-junit"))
}

tasks.test {
    jvmArgs("-Dbase=true", "-Dtest=true")
    systemProperty("shared", "test")
    environment("SHARED", "base")
    environment("TEST_ONLY", "present")
}
