// Generated by ktc-to-gradle 0.12.0. Safe to regenerate.
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

rootProject.name = "junit4"
