// Generated by ktc-to-gradle 0.13.0. Safe to regenerate.
pluginManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

rootProject.name = "compiler-plugin"
