// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    kotlin("multiplatform") version "2.4.10"
    id("com.android.kotlin.multiplatform.library") version "9.0.0"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    androidLibrary {
        namespace = "example.androidonly"
        compileSdk = 37
        minSdk = 24
        withHostTestBuilder {}.configure {}
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("21"))
            freeCompilerArgs.add("-Xjdk-release=21")
        }
    }
    jvmToolchain(25)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("androidMain").apply {
            dependsOn(getByName("commonMain"))
            kotlin.srcDir("src@android")
        }
        maybeCreate("androidHostTest").apply {
            dependsOn(getByName("commonTest"))
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
