// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    kotlin("multiplatform") version "2.4.10"
    id("com.android.kotlin.multiplatform.library") version "9.0.0"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
            freeCompilerArgs.add("-Xjdk-release=25")
        }
    }
    androidLibrary {
        namespace = "example.shared"
        compileSdk = 37
        minSdk = 24
        withHostTestBuilder {}.configure {}
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
            freeCompilerArgs.add("-Xjdk-release=25")
        }
    }
    jvmToolchain(25)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("jvmAndAndroidMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("jvmAndAndroidTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("androidMain").apply {
            dependsOn(getByName("jvmAndAndroidMain"))
        }
        maybeCreate("androidHostTest").apply {
            dependsOn(getByName("jvmAndAndroidTest"))
            dependencies {
                implementation(kotlin("test-junit5"))
            }
        }
        maybeCreate("jvmMain").apply {
            dependsOn(getByName("jvmAndAndroidMain"))
        }
        maybeCreate("jvmTest").apply {
            dependsOn(getByName("jvmAndAndroidTest"))
            dependencies {
                implementation(kotlin("test-junit5"))
            }
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
    systemProperty("mode", "module")
    systemProperty("kept", "module")
}

tasks.withType<Test>().matching { it.name == "jvmTest" }.configureEach {
    jvmArgs("-Xmx512m")
    systemProperty("mode", "jvm")
}

tasks.withType<Test>().matching { it.name == "testAndroidHostTest" }.configureEach {
    jvmArgs("-Xmx512m")
    environment("MODE", "android")
}
