// Generated by ktc-to-gradle 0.13.0. Safe to regenerate.
plugins {
    base
    id("com.android.application") version "9.0.0" apply false
    kotlin("jvm") version "2.4.20" apply false
    kotlin("multiplatform") version "2.4.20" apply false
}
