// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    base
    id("com.android.application") version "9.0.0" apply false
    kotlin("jvm") version "2.4.10" apply false
    kotlin("multiplatform") version "2.4.10" apply false
}
