// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
pluginManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

rootProject.name = "junit-platform-version"

include(":android-app")
project(":android-app").projectDir = file("android-app")

include(":jvm-lib")
project(":jvm-lib").projectDir = file("jvm-lib")

include(":kmp-lib")
project(":kmp-lib").projectDir = file("kmp-lib")
