// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    kotlin("jvm") version "2.4.10"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvmToolchain(25)
    compilerOptions {
        this.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
    }
}

java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
}

sourceSets {
    main {
        kotlin.srcDir("src")
        resources.srcDir("resources")
    }
    test {
        kotlin.srcDir("test")
        resources.srcDir("testResources")
    }
}

dependencies {
    api("com.squareup.okio:okio:3.17.0")
    compileOnly("org.example:compile:1.0")
    runtimeOnly("org.example:runtime:1.0")
    implementation("org.example:plain:1.0")
    implementation(platform("org.example:platform:1.0"))
    implementation(kotlin("reflect"))
    testImplementation(kotlin("test-junit5"))
    testImplementation("org.example:test-exported:1.0")
    testRuntimeOnly("org.example:test-runtime:1.0")
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}
