// Generated by ktc-to-gradle 0.12.0. Safe to regenerate.
plugins {
    kotlin("multiplatform") version "2.4.10"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    wasmJs { binaries.executable(); browser() }
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("webMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("webTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("wasmJsMain").apply {
            dependsOn(getByName("webMain"))
        }
        maybeCreate("wasmJsTest").apply {
            dependsOn(getByName("webTest"))
        }
    }
}
