// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
pluginManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

rootProject.name = "wasm-js-app"
