// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
pluginManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

rootProject.name = "publishing"

include(":jvm-lib")
project(":jvm-lib").projectDir = file("jvm-lib")

include(":kmp-lib")
project(":kmp-lib").projectDir = file("kmp-lib")
