// Generated by ktc-to-gradle 0.13.0. Safe to regenerate.
pluginManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

rootProject.name = "plugin-module"

include(":app")
project(":app").projectDir = file("app")

include(":libs:messages")
project(":libs:messages").projectDir = file("libs/messages")
