// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
pluginManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

rootProject.name = "test-release-android"
