package io.heapy.ktctogradle

import okio.FileSystem
import okio.Path

class Converter(private val fileSystem: FileSystem = systemFileSystem) {
    fun convert(start: Path, force: Boolean = false, dryRun: Boolean = false): ConversionResult {
        val project = ProjectLoader(fileSystem).load(start)
        val (generated, diagnostics) = GradleGenerator(fileSystem).generate(project)
        val changed = generated.filter { generatedFile ->
            !fileSystem.exists(generatedFile.path) || fileSystem.read(generatedFile.path) { readUtf8() } != generatedFile.content
        }
        val collisions = changed.filter { fileSystem.exists(it.path) && !isGenerated(fileSystem.read(it.path) { readUtf8() }) }
        if (collisions.isNotEmpty() && !force) {
            throw ConversionException(
                "Refusing to overwrite existing files: ${collisions.joinToString { it.path.relativeTo(project.root).toString() }}. " +
                    "Re-run with --force after reviewing them.",
            )
        }
        if (!dryRun) {
            for (file in changed) {
                file.path.parent?.let(fileSystem::createDirectories)
                fileSystem.write(file.path) { writeUtf8(file.content) }
            }
            makeExecutable(project.root / "gradlew")
        }
        return ConversionResult(
            root = project.root.toString(),
            writtenFiles = changed.map { it.path.relativeTo(project.root).toString() },
            diagnostics = diagnostics,
        )
    }

    private fun isGenerated(content: String): Boolean =
        content.contains("Generated by ktc-to-gradle") || content.contains("generated by ktc-to-gradle", ignoreCase = true)
}
