// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
plugins {
    kotlin("multiplatform")
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
            freeCompilerArgs.add("-Xjdk-release=17")
        }
    }
    linuxX64 {
    }
    jvmToolchain(25)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("jvmMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("jvmTest").apply {
            dependsOn(getByName("commonTest"))
            kotlin.srcDir("test@jvm")
            dependencies {
                runtimeOnly("org.junit.platform:junit-platform-launcher")
                implementation("org.junit.jupiter:junit-jupiter:5.14.1")
            }
        }
        maybeCreate("nativeMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("nativeTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("linuxMain").apply {
            dependsOn(getByName("nativeMain"))
        }
        maybeCreate("linuxTest").apply {
            dependsOn(getByName("nativeTest"))
        }
        maybeCreate("linuxX64Main").apply {
            dependsOn(getByName("linuxMain"))
        }
        maybeCreate("linuxX64Test").apply {
            dependsOn(getByName("linuxTest"))
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
