// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
plugins {
    kotlin("jvm")
    `maven-publish`
    signing
}

group = "example.publishing"
version = "1.2.3"

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvmToolchain(25)
    compilerOptions {
        this.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        freeCompilerArgs.add("-Xjdk-release=17")
    }
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
    targetCompatibility = JavaVersion.toVersion("17")
    withSourcesJar()
    withJavadocJar()
}

tasks.compileJava {
    options.release.set(17)
}

sourceSets {
    main {
        kotlin.srcDir("src")
        resources.srcDir("resources")
    }
    test {
        kotlin.srcDir("test")
        resources.srcDir("testResources")
    }
}

dependencies {
    testImplementation(kotlin("test-junit5"))
}

tasks.test {
    useJUnitPlatform()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifactId = "published-library"
            pom {
                name.set("published-library")
                description.set("A converted library that still publishes")
                url.set("https://example.invalid/published-library")
                licenses {
                    license {
                        name.set("The Apache License, Version 2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                    }
                }
                developers {
                    developer {
                        id.set("example")
                        name.set("Example Developer")
                        url.set("https://example.invalid/example")
                        email.set("developer@example.invalid")
                        organization.set("Example Org")
                        organizationUrl.set("https://example.invalid")
                    }
                }
                scm {
                    url.set("https://example.invalid/published-library.git")
                    connection.set("scm:git:https://example.invalid/published-library.git")
                    developerConnection.set("scm:git:https://example.invalid/published-library.git")
                }
            }
        }
    }
    repositories {
        maven {
            name = "localFile"
            url = uri("build/repo")
        }
    }
}

signing {
    val signingKey = providers.environmentVariable("KOTLIN_TOOLCHAIN_SIGNING_KEY").orNull
    if (signingKey != null) {
        useInMemoryPgpKeys(signingKey, providers.environmentVariable("KOTLIN_TOOLCHAIN_SIGNING_KEY_PASSPHRASE").getOrElse(""))
    }
    sign(publishing.publications)
}
