// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
plugins {
    kotlin("multiplatform")
    `maven-publish`
    signing
}

group = "example.central"
version = "1.0.0"

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
            freeCompilerArgs.add("-Xjdk-release=25")
        }
    }
    jvmToolchain(25)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("jvmMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("jvmTest").apply {
            dependsOn(getByName("commonTest"))
            dependencies {
                implementation(kotlin("test-junit5"))
            }
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        pom {
            name.set("kmp-lib")
            description.set("A converted library that publishes to Maven Central")
            url.set("https://example.invalid/shared")
            licenses {
                license {
                    name.set("The Apache License, Version 2.0")
                    url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                }
            }
            developers {
                developer {
                    id.set("example")
                    name.set("Example Developer")
                }
            }
            scm {
                url.set("https://example.invalid/shared.git")
                connection.set("scm:git:https://example.invalid/shared.git")
                developerConnection.set("scm:git:https://example.invalid/shared.git")
            }
        }
    }
}

signing {
    val signingKey = providers.environmentVariable("KOTLIN_TOOLCHAIN_SIGNING_KEY").orNull
    if (signingKey != null) {
        useInMemoryPgpKeys(signingKey, providers.environmentVariable("KOTLIN_TOOLCHAIN_SIGNING_KEY_PASSPHRASE").getOrElse(""))
    }
    sign(publishing.publications)
}
