// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
pluginManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

rootProject.name = "mixed-modules"

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") { from(files("libs.versions.toml")) }
    }
}

include(":app")
project(":app").projectDir = file("app")

include(":libs:core")
project(":libs:core").projectDir = file("libs/core")

include(":libs:shared")
project(":libs:shared").projectDir = file("libs/shared")
