// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    kotlin("multiplatform") version "2.4.10"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    js(IR) { binaries.executable(); browser() }
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("webMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("webTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("jsMain").apply {
            dependsOn(getByName("webMain"))
        }
        maybeCreate("jsTest").apply {
            dependsOn(getByName("webTest"))
        }
    }
}
