// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
plugins {
    kotlin("multiplatform") version "2.4.10"
    id("com.android.kotlin.multiplatform.library") version "9.0.0"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
            freeCompilerArgs.add("-Xjdk-release=25")
        }
    }
    androidLibrary {
        namespace = "io.heapy.example.compilesdk"
        compileSdk = 34
        minSdk = 24
        withHostTestBuilder {}.configure {}
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
            freeCompilerArgs.add("-Xjdk-release=25")
        }
    }
    jvmToolchain(25)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("androidMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("androidHostTest").apply {
            dependsOn(getByName("commonTest"))
            dependencies {
                implementation(kotlin("test-junit5"))
            }
        }
        maybeCreate("jvmMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("jvmTest").apply {
            dependsOn(getByName("commonTest"))
            dependencies {
                implementation(kotlin("test-junit5"))
            }
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
