// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    id("com.android.application") version "9.0.0"
}

repositories {
    mavenCentral()
    google()
}

android {
    namespace = "example.androidjunit4"
    compileSdk = 37
    defaultConfig {
        applicationId = "example.androidjunit4"
        minSdk = 24
        targetSdk = 37
        versionCode = 1
        versionName = "unspecified"
    }
    compileOptions {
        sourceCompatibility = JavaVersion.toVersion("17")
        targetCompatibility = JavaVersion.toVersion("17")
    }
    sourceSets.named("main") {
        kotlin.srcDirs("src", "src@android")
        resources.srcDirs("resources", "resources@android")
        manifest.srcFile("src/AndroidManifest.xml")
    }
    sourceSets.named("test") {
        kotlin.srcDirs("test", "test@android")
        resources.srcDirs("testResources", "testResources@android")
    }
}

kotlin {
    compilerOptions {
        this.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
    }
}

dependencies {
    testImplementation(kotlin("test-junit"))
}
