// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.

import java.util.Properties

plugins {
    kotlin("jvm") version "2.4.10"
    `maven-publish`
}

group = "org.example"
version = "1.0.0"

repositories {
    mavenCentral()
    google()
    maven {
        name = "https://repo.example.com"
        url = uri("https://repo.example.com")
        val repositoryCredentials2 = Properties()
        file("local.properties").inputStream().use(repositoryCredentials2::load)
        credentials {
            username = repositoryCredentials2.getProperty("user")
            password = repositoryCredentials2.getProperty("password")
        }
    }
}

kotlin {
    jvmToolchain(25)
    compilerOptions {
        languageVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.fromVersion("2.0"))
        this.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
    }
}

java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
    withJavadocJar()
}

sourceSets {
    main {
        kotlin.srcDir("src")
        resources.srcDir("resources")
    }
    test {
        kotlin.srcDir("test")
        resources.srcDir("testResources")
    }
}

dependencies {
    testImplementation(kotlin("test-junit5"))
}

tasks.test {
    useJUnitPlatform()
    jvmArgs("-Xmx2g")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            pom {
                name.set("Library")
                developers {
                    developer {
                        id.set("jane")
                    }
                }
            }
        }
    }
}
