// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
pluginManagement {
    repositories {
        mavenCentral()
        google()
        maven {
            name = "https://repo.example.com"
            url = uri("https://repo.example.com")
            val repositoryCredentials2 = java.util.Properties()
            file("local.properties").inputStream().use(repositoryCredentials2::load)
            credentials {
                username = repositoryCredentials2.getProperty("user")
                password = repositoryCredentials2.getProperty("password")
            }
        }
        gradlePluginPortal()
    }
}

rootProject.name = "unknown-keys"
