// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    kotlin("multiplatform") version "2.4.10"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
            freeCompilerArgs.add("-Xjdk-release=25")
        }
    }
    linuxX64 {
    }
    jvmToolchain(25)
    compilerOptions {
        freeCompilerArgs.addAll(listOf("-P", "plugin:org.example.first:moduleId=shared", "-P", "plugin:org.example.first:mode=strict"))
    }
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("jvmMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("jvmTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("nativeMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("nativeTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("linuxMain").apply {
            dependsOn(getByName("nativeMain"))
        }
        maybeCreate("linuxTest").apply {
            dependsOn(getByName("nativeTest"))
        }
        maybeCreate("linuxX64Main").apply {
            dependsOn(getByName("linuxMain"))
        }
        maybeCreate("linuxX64Test").apply {
            dependsOn(getByName("linuxTest"))
        }
    }
}

dependencies {
    kotlinCompilerPluginClasspath("org.example:first-compiler:1.0")
    kotlinNativeCompilerPluginClasspath("org.example:first-compiler:1.0")
    kotlinCompilerPluginClasspath("org.example:second-compiler:2.0")
    kotlinNativeCompilerPluginClasspath("org.example:second-compiler:2.0")
}
