// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
plugins {
    kotlin("multiplatform")
    `maven-publish`
}

group = "example.publishing"
version = "1.2.3"

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
        compilations.named("main").configure {
            compileTaskProvider.configure {
                compilerOptions {
                    freeCompilerArgs.add("-Xjdk-release=17")
                }
            }
        }
        compilations.named("test").configure {
            compileTaskProvider.configure {
                compilerOptions {
                    jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
                    freeCompilerArgs.add("-Xjdk-release=25")
                }
            }
        }
    }
    linuxX64 {
    }
    jvmToolchain(25)
    withSourcesJar(publish = false)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("jvmMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("jvmTest").apply {
            dependsOn(getByName("commonTest"))
            dependencies {
                implementation(kotlin("test-junit5"))
            }
        }
        maybeCreate("nativeMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("nativeTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("linuxMain").apply {
            dependsOn(getByName("nativeMain"))
        }
        maybeCreate("linuxTest").apply {
            dependsOn(getByName("nativeTest"))
        }
        maybeCreate("linuxX64Main").apply {
            dependsOn(getByName("linuxMain"))
        }
        maybeCreate("linuxX64Test").apply {
            dependsOn(getByName("linuxTest"))
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        artifactId = "published-multiplatform" + artifactId.removePrefix("kmp-lib")
        pom {
            name.set("published-multiplatform")
            url.set("https://example.invalid/published-multiplatform")
            scm {
                url.set("https://example.invalid/published-multiplatform")
                connection.set("scm:git:https://example.invalid/published-multiplatform.git")
                developerConnection.set("scm:git:ssh://git@example.invalid/published-multiplatform.git")
            }
        }
    }
    repositories {
        maven {
            name = "localFile"
            url = uri("build/repo")
        }
    }
}
