// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
plugins {
    kotlin("jvm") version "2.4.10"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvmToolchain(25)
    compilerOptions {
        this.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
        freeCompilerArgs.add("-Xjdk-release=25")
    }
}

java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
}

tasks.compileJava {
    options.release.set(25)
}

sourceSets {
    main {
        kotlin.srcDir("src")
        resources.srcDir("resources")
    }
    test {
        kotlin.srcDir("test")
        resources.srcDir("testResources")
    }
}

dependencies {
    implementation(libs.okio)
    implementation(kotlin("reflect"))
    testImplementation(kotlin("test-junit5"))
    testImplementation(libs.junit.jupiter.api)
}

tasks.test {
    useJUnitPlatform()
}
