// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
            freeCompilerArgs.add("-Xjdk-release=17")
        }
    }
    linuxX64 {
    }
    jvmToolchain(25)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.11.0")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("desktopMain").apply {
            dependsOn(getByName("commonMain"))
            kotlin.srcDir("src@desktop")
        }
        maybeCreate("desktopTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("jvmMain").apply {
            dependsOn(getByName("desktopMain"))
            kotlin.srcDir("src@jvm")
        }
        maybeCreate("jvmTest").apply {
            dependsOn(getByName("desktopTest"))
            dependencies {
                implementation(kotlin("test-junit5"))
            }
        }
        maybeCreate("nativeMain").apply {
            dependsOn(getByName("desktopMain"))
        }
        maybeCreate("nativeTest").apply {
            dependsOn(getByName("desktopTest"))
        }
        maybeCreate("linuxMain").apply {
            dependsOn(getByName("nativeMain"))
        }
        maybeCreate("linuxTest").apply {
            dependsOn(getByName("nativeTest"))
        }
        maybeCreate("linuxX64Main").apply {
            dependsOn(getByName("linuxMain"))
            kotlin.srcDir("src@linuxX64")
        }
        maybeCreate("linuxX64Test").apply {
            dependsOn(getByName("linuxTest"))
        }
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
