// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
plugins {
    kotlin("multiplatform") version "2.4.10"
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    wasmWasi {
        binaries.executable()
        compilations.configureEach {
            compileTaskProvider.configure {
                compilerOptions {
                    allWarningsAsErrors.set(true)
                }
            }
        }
    }
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("wasmWasiMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("wasmWasiTest").apply {
            dependsOn(getByName("commonTest"))
        }
    }
}
