// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

rootProject.name = "wasm-wasi-app"
