// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
plugins {
    id("com.android.application")
}

repositories {
    mavenCentral()
    google()
}

android {
    namespace = "example.junitplatformversion"
    compileSdk = 37
    defaultConfig {
        applicationId = "example.junitplatformversion"
        minSdk = 24
        targetSdk = 37
        versionCode = 1
        versionName = "unspecified"
    }
    compileOptions {
        sourceCompatibility = JavaVersion.toVersion("17")
        targetCompatibility = JavaVersion.toVersion("17")
    }
    sourceSets.named("main") {
        kotlin.srcDirs("src", "src@android")
        resources.srcDirs("resources", "resources@android")
        manifest.srcFile("src/AndroidManifest.xml")
    }
    sourceSets.named("test") {
        kotlin.srcDirs("test", "test@android")
        resources.srcDirs("testResources", "testResources@android")
    }
    testOptions {
        unitTests.all {
            it.useJUnitPlatform()
        }
    }
}

kotlin {
    compilerOptions {
        this.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
    }
}

dependencies {
    testImplementation(kotlin("test-junit5"))
}
