// Generated by ktc-to-gradle 0.12.0-3. Safe to regenerate.
pluginManagement {
    repositories {
        mavenCentral()
        google()
        maven {
            name = "mavenCentral"
            url = uri("https://mirror.example/maven")
            val repositoryCredentials2 = java.util.Properties()
            file("libs/core/credentials.properties").inputStream().use(repositoryCredentials2::load)
            credentials {
                username = repositoryCredentials2.getProperty("mirror.username")
                password = repositoryCredentials2.getProperty("mirror.password")
            }
        }
        gradlePluginPortal()
    }
}

rootProject.name = "plugin-repositories"

include(":app")
project(":app").projectDir = file("app")

include(":libs:core")
project(":libs:core").projectDir = file("libs/core")
