// Generated by ktc-to-gradle 0.12.0. Safe to regenerate.
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

rootProject.name = "jvm-multi"

include(":app")
project(":app").projectDir = file("app")

include(":libs:messages")
project(":libs:messages").projectDir = file("libs/messages")
