// Generated by ktc-to-gradle 0.12.0. Safe to regenerate.
plugins {
    id("com.android.application") version "9.0.0"
    kotlin("plugin.serialization") version "2.4.10"
}

repositories {
    mavenCentral()
    google()
}

android {
    namespace = "example.android"
    compileSdk = 36
    defaultConfig {
        applicationId = "example.android"
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = "unspecified"
    }
    compileOptions {
        sourceCompatibility = JavaVersion.toVersion("17")
        targetCompatibility = JavaVersion.toVersion("17")
    }
    sourceSets.named("main") {
        kotlin.srcDirs("src", "src@android")
        resources.srcDirs("resources", "resources@android")
        manifest.srcFile("src/AndroidManifest.xml")
    }
    sourceSets.named("test") {
        kotlin.srcDirs("test", "test@android")
        resources.srcDirs("testResources", "testResources@android")
    }
}

kotlin {
    compilerOptions {
        this.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
    }
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.11.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
    testImplementation(kotlin("test-junit5"))
}
