// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
}

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
            freeCompilerArgs.add("-Xjdk-release=25")
        }
    }
    js(IR) { browser() }
    jvmToolchain(25)
    sourceSets {
        commonMain {
            kotlin.srcDir("src")
            resources.srcDir("resources")
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.11.0")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
            }
        }
        commonTest {
            kotlin.srcDir("test")
            resources.srcDir("testResources")
            dependencies {
                implementation(kotlin("test"))
            }
        }
        maybeCreate("jvmMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("jvmTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("webMain").apply {
            dependsOn(getByName("commonMain"))
        }
        maybeCreate("webTest").apply {
            dependsOn(getByName("commonTest"))
        }
        maybeCreate("jsMain").apply {
            dependsOn(getByName("webMain"))
        }
        maybeCreate("jsTest").apply {
            dependsOn(getByName("webTest"))
        }
    }
}
