// Generated by ktc-to-gradle 0.13.0. Safe to regenerate.
plugins {
    base
    kotlin("multiplatform") version "2.4.20" apply false
    id("com.android.kotlin.multiplatform.library") version "9.0.0" apply false
}
