// Generated by ktc-to-gradle 0.13.0. Safe to regenerate.
pluginManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

rootProject.name = "kmp-android-namespace"

include(":libs:custom")
project(":libs:custom").projectDir = file("libs/custom")

include(":libs:published")
project(":libs:published").projectDir = file("libs/published")

include(":libs:unpublished")
project(":libs:unpublished").projectDir = file("libs/unpublished")
