// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.

import java.util.Properties

plugins {
    kotlin("jvm")
}

repositories {
    maven {
        name = "mavenCentral"
        url = uri("https://mirror.example/maven")
        val repositoryCredentials0 = Properties()
        file("credentials.properties").inputStream().use(repositoryCredentials0::load)
        credentials {
            username = repositoryCredentials0.getProperty("mirror.username")
            password = repositoryCredentials0.getProperty("mirror.password")
        }
    }
}

kotlin {
    jvmToolchain(25)
    compilerOptions {
        this.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("25"))
        freeCompilerArgs.add("-Xjdk-release=25")
    }
}

java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
}

tasks.compileJava {
    options.release.set(25)
}

sourceSets {
    main {
        kotlin.srcDir("src")
        resources.srcDir("resources")
    }
    test {
        kotlin.srcDir("test")
        resources.srcDir("testResources")
    }
}

dependencies {
    testImplementation(kotlin("test-junit5"))
}

tasks.test {
    useJUnitPlatform()
}
