package io.heapy.ktctogradle.render

import io.heapy.ktctogradle.Versions
import io.heapy.ktctogradle.model.GradleModule
import io.heapy.ktctogradle.model.GradleProject
import io.heapy.ktctogradle.model.Repository
import io.heapy.ktctogradle.model.RepositoryCredentials
import io.heapy.ktctogradle.model.RepositoryShorthand
import okio.Path
import okio.Path.Companion.toPath
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Where a version catalog has to be declared, which is the one decision `settings.gradle.kts`
 * makes on its own.
 *
 * The golden baselines pin the file a project with a root catalog gets, but they cannot state that
 * a catalog under `gradle/` has to change nothing at all — no baseline can show the absence of a
 * block it never contained. That is what this suite says.
 */
class SettingsRendererTest {
    @Test
    fun aCatalogNextToTheSettingsFileIsDeclared() {
        assertEquals(
            """
            // Generated by ktc-to-gradle ${Versions.CONVERTER}. Safe to regenerate.
            pluginManagement {
                repositories {
                    mavenCentral()
                    google()
                    gradlePluginPortal()
                }
            }

            rootProject.name = "demo"

            dependencyResolutionManagement {
                versionCatalogs {
                    create("libs") { from(files("libs.versions.toml")) }
                }
            }

            """.trimIndent(),
            renderSettings(project(catalog = ROOT / "libs.versions.toml")),
        )
    }

    @Test
    fun aCatalogUnderGradleIsLeftToGradleToFind() {
        assertEquals(
            renderSettings(project(catalog = null)),
            renderSettings(project(catalog = ROOT / "gradle" / "libs.versions.toml")),
            "Gradle finds gradle/libs.versions.toml itself, so declaring it again is an error",
        )
    }

    /**
     * Gradle compiles `pluginManagement { }` on its own, ahead of the rest of the settings file and
     * without its import list, so a settings script that imports `java.util.Properties` and then
     * writes `Properties()` inside the block fails to compile with an unresolved reference. Nothing
     * about the emitted bytes says why the name has to be written out in full, so it is said here.
     */
    @Test
    fun credentialsInPluginManagementNameTheirTypeInFull() {
        assertEquals(
            """
            // Generated by ktc-to-gradle ${Versions.CONVERTER}. Safe to regenerate.
            pluginManagement {
                repositories {
                    maven {
                        name = "mavenCentral"
                        url = uri("https://mirror.example/maven")
                        val repositoryCredentials0 = java.util.Properties()
                        file("credentials.properties").inputStream().use(repositoryCredentials0::load)
                        credentials {
                            username = repositoryCredentials0.getProperty("user")
                            password = repositoryCredentials0.getProperty("password")
                        }
                    }
                    gradlePluginPortal()
                }
            }

            rootProject.name = "demo"

            """.trimIndent(),
            renderSettings(project(catalog = null, pluginRepositories = listOf(MIRROR))),
        )
    }

    private fun project(
        catalog: Path?,
        pluginRepositories: List<Repository> = DEFAULT_REPOSITORIES,
    ): GradleProject = GradleProject(
        root = ROOT,
        name = "demo",
        catalog = catalog,
        modules = listOf(
            GradleModule(
                gradlePath = ":",
                directory = ROOT,
                plugins = emptyList(),
                repositories = emptyList(),
                requiresCredentialsImport = false,
                build = null,
            ),
        ),
        pluginRepositories = pluginRepositories,
    )

    private companion object {
        private val ROOT: Path = "/workspace".toPath()

        private val DEFAULT_REPOSITORIES = listOf(
            Repository("mavenCentral", "https://repo1.maven.org/maven2", shorthand = RepositoryShorthand.MAVEN_CENTRAL),
            Repository("mavenGoogle", "https://maven.google.com", shorthand = RepositoryShorthand.GOOGLE),
        )

        private val MIRROR = Repository(
            id = "mavenCentral",
            url = "https://mirror.example/maven",
            credentials = RepositoryCredentials("credentials.properties", "user", "password"),
        )
    }
}
