package io.heapy.ktctogradle.render

import io.heapy.ktctogradle.Versions
import io.heapy.ktctogradle.model.GradleModule
import io.heapy.ktctogradle.model.GradleProject
import okio.Path
import okio.Path.Companion.toPath
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Where a version catalog has to be declared, which is the one decision `settings.gradle.kts`
 * makes on its own.
 *
 * The golden baselines pin the file a project with a root catalog gets, but they cannot state that
 * a catalog under `gradle/` has to change nothing at all — no baseline can show the absence of a
 * block it never contained. That is what this suite says.
 */
class SettingsRendererTest {
    @Test
    fun aCatalogNextToTheSettingsFileIsDeclared() {
        assertEquals(
            """
            // Generated by ktc-to-gradle ${Versions.CONVERTER}. Safe to regenerate.
            pluginManagement {
                repositories {
                    gradlePluginPortal()
                    google()
                    mavenCentral()
                }
            }

            rootProject.name = "demo"

            dependencyResolutionManagement {
                versionCatalogs {
                    create("libs") { from(files("libs.versions.toml")) }
                }
            }

            """.trimIndent(),
            renderSettings(project(catalog = ROOT / "libs.versions.toml")),
        )
    }

    @Test
    fun aCatalogUnderGradleIsLeftToGradleToFind() {
        assertEquals(
            renderSettings(project(catalog = null)),
            renderSettings(project(catalog = ROOT / "gradle" / "libs.versions.toml")),
            "Gradle finds gradle/libs.versions.toml itself, so declaring it again is an error",
        )
    }

    private fun project(catalog: Path?): GradleProject = GradleProject(
        root = ROOT,
        name = "demo",
        catalog = catalog,
        modules = listOf(
            GradleModule(
                gradlePath = ":",
                directory = ROOT,
                plugins = emptyList(),
                repositories = emptyList(),
                requiresCredentialsImport = false,
                build = null,
            ),
        ),
    )

    private companion object {
        private val ROOT: Path = "/workspace".toPath()
    }
}
