package io.heapy.ktctogradle.render

import io.heapy.ktctogradle.Versions

internal object StaticAssets {
    /**
     * The phrase every generated file carries, and the only thing `write/FileWriter` looks for
     * before it replaces a file. The two stages read it from here so the refusal protocol cannot
     * drift: a header that stopped saying this would make the converter refuse its own output.
     */
    const val GENERATED_MARKER = "Generated by ktc-to-gradle"

    /**
     * `kotlin.mpp.applyDefaultHierarchyTemplate=false` is written for every project, not only the
     * multiplatform ones.
     *
     * It changes no wiring. The converter gives every non-common fragment an explicit `dependsOn`
     * edge, and the Kotlin Gradle Plugin does not apply its default hierarchy template to a module
     * that has them: it reports the mismatch and falls back to the plain edges instead. Setting the
     * property picks that same fallback up front, so the only thing that goes away is a warning
     * fired once per multiplatform module of every conversion.
     *
     * Dropping the explicit edges and living inside the template would be the other way to silence
     * it, and a much larger change: those edges carry the intermediate and alias source sets the
     * converter builds on purpose.
     *
     * Written unconditionally because it is inert without one: the plugin reads it only after
     * finding a multiplatform extension, so a `jvm/lib` never reaches it.
     */
    fun generatedGradleProperties(): String = """
        # ${GENERATED_MARKER}. Safe to regenerate.
        org.gradle.configuration-cache=true
        org.gradle.caching=true
        org.gradle.jvmargs=-Xmx3g
        kotlin.daemon.jvmargs=-Xmx4g
        kotlin.code.style=official
        kotlin.mpp.applyDefaultHierarchyTemplate=false
    """.trimIndent() + "\n"

    /**
     * The one wrapper file the converter writes itself rather than embedding.
     *
     * It carries `distributionSha256Sum`, which `gradle wrapper` does not write: the converter
     * knows the checksum of the release it embedded, and a wrapper that verifies what it
     * downloaded is worth the one line of divergence. `retries` is 3 and not Gradle's own 0,
     * which is the retry behaviour the hand-written launcher had before this file replaced it.
     */
    fun wrapperProperties(): String = """
        # ${GENERATED_MARKER}. Safe to regenerate.
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-${Versions.GRADLE}-bin.zip
        distributionSha256Sum=${Versions.GRADLE_SHA256}
        networkTimeout=10000
        retries=3
        retryBackOffMs=500
        validateDistributionUrl=true
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
    """.trimIndent() + "\n"

    fun header(): String = "// $GENERATED_MARKER ${Versions.CONVERTER}. Safe to regenerate."
}
