package io.heapy.ktctogradle.render

import io.heapy.ktctogradle.Versions

internal object StaticAssets {
    /** Shared ownership marker for rendering and overwrite checks. */
    const val GENERATED_MARKER = "Generated by ktc-to-gradle"

    /**
     * Disables KGP inference the converter replaces explicitly. The hierarchy property suppresses
     * warnings for the emitted `dependsOn` graph, including aliases. The test property prevents
     * `junit: none` from acquiring an inferred JUnit adapter; other frameworks name theirs directly.
     * Both properties are inert where their plugins or features are absent.
     */
    fun generatedGradleProperties(): String = """
        # ${GENERATED_MARKER}. Safe to regenerate.
        org.gradle.configuration-cache=true
        org.gradle.caching=true
        org.gradle.jvmargs=-Xmx3g
        kotlin.daemon.jvmargs=-Xmx4g
        kotlin.code.style=official
        kotlin.mpp.applyDefaultHierarchyTemplate=false
        kotlin.test.infer.jvm.variant=false
    """.trimIndent() + "\n"

    /** Adds distribution verification and three download retries to Gradle's wrapper properties. */
    fun wrapperProperties(): String = """
        # ${GENERATED_MARKER}. Safe to regenerate.
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-${Versions.GRADLE}-bin.zip
        distributionSha256Sum=${Versions.GRADLE_SHA256}
        networkTimeout=10000
        retries=3
        retryBackOffMs=500
        validateDistributionUrl=true
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
    """.trimIndent() + "\n"

    fun header(): String = "// $GENERATED_MARKER ${Versions.CONVERTER}. Safe to regenerate."
}
