#!/usr/bin/env sh
# Regenerates the Gradle wrapper the converter ships.
#
# The converter lays down the four files `gradle wrapper` produces rather than a launcher of its
# own, so those files have to be carried inside the binary. This script is the only thing that
# writes them: run it, read the diff, commit. Never hand-edit GradleWrapperAssets.kt.
#
#   tools/update-gradle-wrapper.sh            # latest stable, from services.gradle.org
#   tools/update-gradle-wrapper.sh 9.7.1      # a named version
#
# Needs: curl, unzip, sha256sum or shasum, base64, and a JVM (the wrapper is generated by Gradle).
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
ASSETS="$ROOT/core/src/io/heapy/ktctogradle/render/GradleWrapperAssets.kt"
VERSIONS="$ROOT/core/src/io/heapy/ktctogradle/Versions.kt"
MARKER="Generated by ktc-to-gradle"

for tool in curl unzip base64; do
  command -v "$tool" >/dev/null 2>&1 || { echo "update-gradle-wrapper: $tool is required" >&2; exit 1; }
done
if command -v sha256sum >/dev/null 2>&1; then
  sha256() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum >/dev/null 2>&1; then
  sha256() { shasum -a 256 "$1" | cut -d' ' -f1; }
else
  echo "update-gradle-wrapper: sha256sum or shasum is required" >&2
  exit 1
fi

WORK=$(mktemp -d)
trap 'STATUS=$?; rm -rf "$WORK" || :; exit $STATUS' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

# services.gradle.org publishes the distribution checksum and the wrapper-jar checksum next to the
# version, so both halves of what gets embedded are verified against the publisher and not against
# whatever the download happened to produce.
if [ $# -ge 1 ]; then
  VERSION=$1
  DISTRIBUTION_URL="https://services.gradle.org/distributions/gradle-$VERSION-bin.zip"
  DISTRIBUTION_SHA256=$(curl -fsSL --retry 3 "$DISTRIBUTION_URL.sha256")
  WRAPPER_SHA256=$(curl -fsSL --retry 3 "https://services.gradle.org/distributions/gradle-$VERSION-wrapper.jar.sha256")
else
  # `current` is the latest final release: it never names a release candidate or a nightly.
  CURRENT="$WORK/current.json"
  curl -fsSL --retry 3 https://services.gradle.org/versions/current > "$CURRENT"
  json() { sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$CURRENT" | head -n 1; }
  VERSION=$(json version)
  DISTRIBUTION_URL=$(json downloadUrl)
  DISTRIBUTION_SHA256=$(json checksum)
  WRAPPER_SHA256=$(json wrapperChecksum)
fi
[ -n "$VERSION" ] && [ -n "$DISTRIBUTION_URL" ] && [ -n "$DISTRIBUTION_SHA256" ] && [ -n "$WRAPPER_SHA256" ] ||
  { echo "update-gradle-wrapper: could not resolve the Gradle release to use" >&2; exit 1; }
echo "update-gradle-wrapper: Gradle $VERSION"

ARCHIVE="$WORK/gradle-$VERSION-bin.zip"
curl -fsSL --retry 3 -o "$ARCHIVE" "$DISTRIBUTION_URL"
ACTUAL=$(sha256 "$ARCHIVE")
[ "$ACTUAL" = "$DISTRIBUTION_SHA256" ] ||
  { echo "update-gradle-wrapper: distribution checksum mismatch: $ACTUAL != $DISTRIBUTION_SHA256" >&2; exit 1; }
unzip -q "$ARCHIVE" -d "$WORK/dist"

# `gradle wrapper` writes the four files, and it refuses to run without a settings file.
PROJECT="$WORK/project"
mkdir -p "$PROJECT"
: > "$PROJECT/settings.gradle.kts"
(cd "$PROJECT" && "$WORK/dist/gradle-$VERSION/bin/gradle" wrapper --gradle-version "$VERSION" -q --console=plain)

JAR="$PROJECT/gradle/wrapper/gradle-wrapper.jar"
ACTUAL=$(sha256 "$JAR")
[ "$ACTUAL" = "$WRAPPER_SHA256" ] ||
  { echo "update-gradle-wrapper: wrapper jar checksum mismatch: $ACTUAL != $WRAPPER_SHA256" >&2; exit 1; }

# Gradle's own scripts carry no ownership marker, and `write/FileWriter` refuses to replace a file
# that has none — the converter would refuse its own output on the second run. The marker goes in
# first, in each file's own comment syntax, and gradlew.bat keeps CRLF throughout.
{
  head -n 1 "$PROJECT/gradlew"
  printf '# %s. Safe to regenerate.\n' "$MARKER"
  tail -n +2 "$PROJECT/gradlew"
} > "$WORK/sh"
mv "$WORK/sh" "$PROJECT/gradlew"
printf '@rem %s. Safe to regenerate.\r\n' "$MARKER" > "$WORK/bat"
cat "$PROJECT/gradlew.bat" >> "$WORK/bat"
mv "$WORK/bat" "$PROJECT/gradlew.bat"

# Base64 rather than a Kotlin raw string: one encoding for all three files, immune to the `$` and
# the quoting in gradlew and to the CRLF in gradlew.bat. Chunked because kotlinc folds a literal
# `+` concatenation back into one constant and the JVM caps a constant at 65535 bytes.
emit() {
  printf '    private val %s = listOf(\n' "$1"
  base64 < "$2" | tr -d '\r\n' | fold -w 96 | sed 's/^/        "/; s/$/",/'
  printf '    ).joinToString("")\n'
}

cat > "$WORK/assets.kt" <<KOTLIN
package io.heapy.ktctogradle.render

import okio.ByteString
import okio.ByteString.Companion.decodeBase64

/**
 * The Gradle wrapper the converter lays down, verbatim.
 *
 * GENERATED FILE — rewritten by \`tools/update-gradle-wrapper.sh\`. Do not edit it by hand.
 *
 * These are the files \`gradle wrapper --gradle-version $VERSION\` produced, with one ownership
 * marker comment added to each script so \`write/FileWriter\` recognises them as ours. Gradle owns
 * the logic: reading \`gradle-wrapper.properties\`, downloading, verifying and unpacking the
 * distribution are all its job, and none of it is reimplemented here.
 *
 * Base64 rather than raw strings, because \`gradlew\` is full of \`$\` and quotes and \`gradlew.bat\`
 * ends every line with CRLF. The chunks are joined at run time: kotlinc folds a literal \`+\`
 * concatenation into a single constant, and a constant may not exceed 65535 bytes.
 */
internal object GradleWrapperAssets {
    fun unixLauncher(): String = decode(UNIX_LAUNCHER).utf8()

    fun windowsLauncher(): String = decode(WINDOWS_LAUNCHER).utf8()

    fun wrapperJar(): ByteString = decode(WRAPPER_JAR)

    private fun decode(base64: String): ByteString =
        checkNotNull(base64.decodeBase64()) { "GradleWrapperAssets is corrupt; re-run tools/update-gradle-wrapper.sh" }

$(emit UNIX_LAUNCHER "$PROJECT/gradlew")

$(emit WINDOWS_LAUNCHER "$PROJECT/gradlew.bat")

$(emit WRAPPER_JAR "$JAR")
}
KOTLIN
mv "$WORK/assets.kt" "$ASSETS"

# An unchecked sed is the one way this script can lie: a formatting drift in Versions.kt would
# leave the version stale next to a freshly embedded jar, and nothing would say so.
before=$(sha256 "$VERSIONS")
sed -i.bak \
  -e "s|^\( *const val GRADLE *= \).*|\1\"$VERSION\"|" \
  -e "s|^\( *const val GRADLE_SHA256 *= \).*|\1\"$DISTRIBUTION_SHA256\"|" \
  "$VERSIONS" && rm -f "$VERSIONS.bak"
if ! grep -q "GRADLE = \"$VERSION\"" "$VERSIONS" || ! grep -q "GRADLE_SHA256 = \"$DISTRIBUTION_SHA256\"" "$VERSIONS"; then
  echo "update-gradle-wrapper: could not rewrite GRADLE/GRADLE_SHA256 in $VERSIONS" >&2
  exit 1
fi
if [ "$before" = "$(sha256 "$VERSIONS")" ]; then
  echo "update-gradle-wrapper: $VERSIONS was already current"
fi

echo "update-gradle-wrapper: wrote $ASSETS"
echo "update-gradle-wrapper: now run 'UPDATE_SNAPSHOTS=1 ./kotlin test -m core -p jvm', read the diff, then re-run without the switch"
