package io.heapy.ktctogradle

import io.heapy.ktctogradle.model.FileContent
import io.heapy.ktctogradle.model.GeneratedFile
import io.heapy.ktctogradle.write.FileWriter
import okio.FileSystem
import okio.Path as OkioPath
import okio.Path.Companion.toPath
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.getLastModifiedTime
import kotlin.io.path.readText
import kotlin.io.path.writeText
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * What the write stage is allowed to do to a tree that is already there.
 *
 * It needs a real [FileSystem], so it lives here and not in the common suite.
 */
class FileWriterTest {
    @Test
    fun onlyTheFilesWhoseContentChangedAreReported() {
        val root = temp("unchanged")
        write(root.resolve("build.gradle.kts"), "// Generated by ktc-to-gradle\nold\n")

        val written = writer().write(
            root = root.okio(),
            files = listOf(
                generated(root, "build.gradle.kts", "// Generated by ktc-to-gradle\nnew\n"),
                generated(root, "settings.gradle.kts", "// Generated by ktc-to-gradle\nsettings\n"),
            ),
            force = false,
            dryRun = false,
        )

        assertEquals(listOf("build.gradle.kts", "settings.gradle.kts"), written.map(::notation))
    }

    @Test
    fun aFileThatAlreadyHasTheGeneratedContentIsNotRewritten() {
        val root = temp("identical")
        val target = root.resolve("build.gradle.kts")
        val content = "// Generated by ktc-to-gradle\nsame\n"
        write(target, content)
        val before = target.getLastModifiedTime()

        val written = writer().write(
            root = root.okio(),
            files = listOf(generated(root, "build.gradle.kts", content)),
            force = false,
            dryRun = false,
        )

        assertEquals(emptyList(), written, "Nothing changed, so nothing is written")
        assertEquals(before, target.getLastModifiedTime(), "An unchanged file keeps its timestamp")
    }

    @Test
    fun aFileThisConverterDidNotWriteIsRefused() {
        val root = temp("foreign")
        write(root.resolve("build.gradle.kts"), "plugins { java }\n")

        val failure = kotlin.runCatching {
            writer().write(
                root = root.okio(),
                files = listOf(generated(root, "build.gradle.kts", "// Generated by ktc-to-gradle\n")),
                force = false,
                dryRun = false,
            )
        }.exceptionOrNull()

        assertTrue(failure is ConversionException, "Expected a conversion failure, got $failure")
        assertEquals(
            "Refusing to overwrite existing files: build.gradle.kts. Re-run with --force after reviewing them.",
            failure.message,
        )
        assertEquals("plugins { java }\n", root.resolve("build.gradle.kts").readText(), "The refused file is untouched")
    }

    @Test
    fun aFileThisConverterDidNotWriteIsReplacedWithForce() {
        val root = temp("forced")
        write(root.resolve("build.gradle.kts"), "plugins { java }\n")

        writer().write(
            root = root.okio(),
            files = listOf(generated(root, "build.gradle.kts", "// Generated by ktc-to-gradle\n")),
            force = true,
            dryRun = false,
        )

        assertEquals("// Generated by ktc-to-gradle\n", root.resolve("build.gradle.kts").readText())
    }

    @Test
    fun aDryRunReportsTheSameFilesAndWritesNone() {
        val root = temp("dry-run")

        val written = writer().write(
            root = root.okio(),
            files = listOf(generated(root, "nested/build.gradle.kts", "// Generated by ktc-to-gradle\n")),
            force = false,
            dryRun = true,
        )

        assertEquals(listOf("nested/build.gradle.kts"), written.map(::notation))
        assertFalse(Files.exists(root.resolve("nested")), "A dry run creates no directory either")
    }

    @Test
    fun aDryRunStillRefusesAForeignFile() {
        val root = temp("dry-run-foreign")
        write(root.resolve("build.gradle.kts"), "plugins { java }\n")

        val failure = kotlin.runCatching {
            writer().write(
                root = root.okio(),
                files = listOf(generated(root, "build.gradle.kts", "// Generated by ktc-to-gradle\n")),
                force = false,
                dryRun = true,
            )
        }.exceptionOrNull()

        assertTrue(failure is ConversionException, "A dry run has to report what a real run would refuse")
    }

    /**
     * Every file the converter produces carries the ownership marker [FileWriter] keys on.
     *
     * Written once, then written again with changed content: the second run runs the ownership check
     * over every file on disk, so a generated file that had lost its marker would be refused as
     * foreign instead of regenerated.
     */
    @Test
    fun everyGeneratedFileIsOneTheWriterWillRecogniseAsItsOwn() {
        val source = temp("marker")
        write(source.resolve("module.yaml"), "product: jvm/lib\n")
        val files = Converter(FileSystem.SYSTEM).generateFiles(source.okio()).files

        writer().write(root = source.okio(), files = files, force = false, dryRun = false)
        val rewritten = writer().write(
            root = source.okio(),
            files = files.map(::withChangedContent),
            force = false,
            dryRun = false,
        )

        assertEquals(files.map { notation(it.path.relativeTo(source.okio())) }, rewritten.map(::notation))
    }

    /**
     * The same file with different content, so a second write has something to do.
     *
     * A jar carries no marker and cannot be appended to as text, so its bytes are truncated
     * instead: what the second run has to prove is that the ownership check passes, not what the
     * new content is.
     */
    private fun withChangedContent(file: GeneratedFile): GeneratedFile = GeneratedFile(
        path = file.path,
        content = when (val content = file.content) {
            is FileContent.Text -> FileContent.Text(content.value + "\n")
            is FileContent.Binary -> content.copy(bytes = content.bytes.substring(0, content.bytes.size - 1))
        },
    )

    private fun writer() = FileWriter(FileSystem.SYSTEM)

    /** The written path with `/` on every host, so the assertion does not depend on the separator. */
    private fun notation(path: OkioPath) = path.segments.joinToString("/")

    private fun generated(root: Path, relative: String, content: String) = GeneratedFile(
        path = relative.split('/').fold(root.okio()) { path, segment -> path / segment },
        content = FileContent.Text(content),
    )

    private fun temp(name: String): Path =
        Files.createTempDirectory("ktc-to-gradle-writer-").resolve(name).also(Path::createDirectories)

    private fun Path.okio() = toString().toPath()

    private fun write(path: Path, content: String) {
        path.parent.createDirectories()
        path.writeText(content)
    }
}
