package io.heapy.ktctogradle

import io.heapy.ktctogradle.model.FileContent
import io.heapy.ktctogradle.model.GeneratedFile
import io.heapy.ktctogradle.write.FileWriter
import okio.ByteString.Companion.encodeUtf8
import okio.FileSystem
import okio.Path as OkioPath
import okio.Path.Companion.toPath
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.getLastModifiedTime
import kotlin.io.path.readText
import kotlin.io.path.writeText
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class FileWriterTest {
    @Test
    fun onlyTheFilesWhoseContentChangedAreReported() {
        val root = temp("unchanged")
        write(root.resolve("build.gradle.kts"), "// Generated by ktc-to-gradle\nold\n")

        val written = writer().write(
            root = root.okio(),
            files = listOf(
                generated(root, "build.gradle.kts", "// Generated by ktc-to-gradle\nnew\n"),
                generated(root, "settings.gradle.kts", "// Generated by ktc-to-gradle\nsettings\n"),
            ),
            force = false,
            dryRun = false,
        )

        assertEquals(listOf("build.gradle.kts", "settings.gradle.kts"), written.map(::notation))
    }

    @Test
    fun aFileThatAlreadyHasTheGeneratedContentIsNotRewritten() {
        val root = temp("identical")
        val target = root.resolve("build.gradle.kts")
        val content = "// Generated by ktc-to-gradle\nsame\n"
        write(target, content)
        val before = target.getLastModifiedTime()

        val written = writer().write(
            root = root.okio(),
            files = listOf(generated(root, "build.gradle.kts", content)),
            force = false,
            dryRun = false,
        )

        assertEquals(emptyList(), written, "Nothing changed, so nothing is written")
        assertEquals(before, target.getLastModifiedTime(), "An unchanged file keeps its timestamp")
    }

    @Test
    fun aFileThisConverterDidNotWriteIsRefused() {
        val root = temp("foreign")
        write(root.resolve("build.gradle.kts"), "plugins { java }\n")

        val failure = kotlin.runCatching {
            writer().write(
                root = root.okio(),
                files = listOf(generated(root, "build.gradle.kts", "// Generated by ktc-to-gradle\n")),
                force = false,
                dryRun = false,
            )
        }.exceptionOrNull()

        assertTrue(failure is ConversionException, "Expected a conversion failure, got $failure")
        assertEquals(
            "Refusing to overwrite existing files: build.gradle.kts. Re-run with --force after reviewing them.",
            failure.message,
        )
        assertEquals("plugins { java }\n", root.resolve("build.gradle.kts").readText(), "The refused file is untouched")
    }

    @Test
    fun aFileThisConverterDidNotWriteIsReplacedWithForce() {
        val root = temp("forced")
        write(root.resolve("build.gradle.kts"), "plugins { java }\n")

        writer().write(
            root = root.okio(),
            files = listOf(generated(root, "build.gradle.kts", "// Generated by ktc-to-gradle\n")),
            force = true,
            dryRun = false,
        )

        assertEquals("// Generated by ktc-to-gradle\n", root.resolve("build.gradle.kts").readText())
    }

    @Test
    fun aDryRunReportsTheSameFilesAndWritesNone() {
        val root = temp("dry-run")

        val written = writer().write(
            root = root.okio(),
            files = listOf(generated(root, "nested/build.gradle.kts", "// Generated by ktc-to-gradle\n")),
            force = false,
            dryRun = true,
        )

        assertEquals(listOf("nested/build.gradle.kts"), written.map(::notation))
        assertFalse(Files.exists(root.resolve("nested")), "A dry run creates no directory either")
    }

    @Test
    fun aDryRunStillRefusesAForeignFile() {
        val root = temp("dry-run-foreign")
        write(root.resolve("build.gradle.kts"), "plugins { java }\n")

        val failure = kotlin.runCatching {
            writer().write(
                root = root.okio(),
                files = listOf(generated(root, "build.gradle.kts", "// Generated by ktc-to-gradle\n")),
                force = false,
                dryRun = true,
            )
        }.exceptionOrNull()

        assertTrue(failure is ConversionException, "A dry run has to report what a real run would refuse")
    }

    @Test
    fun anAbsentJarIsWrittenWithoutConsultingAnyCompanion() {
        val root = temp("jar-absent")

        val written = writer().write(
            root = root.okio(),
            files = listOf(jar(root, "new-jar")),
            force = false,
            dryRun = false,
        )

        assertEquals(listOf(JAR), written.map(::notation))
        assertEquals("new-jar", root.resolve(JAR).readText(), "Nothing was there, so nothing had to vouch for it")
    }

    @Test
    fun aJarWhoseBytesAreIdenticalIsNeverOwnershipChecked() {
        val root = temp("jar-identical")
        write(root.resolve(JAR), "same-jar")
        write(root.resolve(PROPERTIES), FOREIGN_PROPERTIES)
        val before = root.resolve(JAR).getLastModifiedTime()

        val written = writer().write(
            root = root.okio(),
            files = listOf(jar(root, "same-jar")),
            force = false,
            dryRun = false,
        )

        assertEquals(emptyList(), written, "An unchanged jar is never checked, foreign companion or not")
        assertEquals(before, root.resolve(JAR).getLastModifiedTime(), "An unchanged file keeps its timestamp")
    }

    @Test
    fun aJarIsReplacedWhenTheCompanionBesideItCarriesTheMarker() {
        val root = temp("jar-ours")
        write(root.resolve(JAR), "old-jar")
        write(root.resolve(PROPERTIES), OUR_PROPERTIES)

        val written = writer().write(
            root = root.okio(),
            files = listOf(jar(root, "new-jar")),
            force = false,
            dryRun = false,
        )

        assertEquals(listOf(JAR), written.map(::notation))
        assertEquals("new-jar", root.resolve(JAR).readText())
    }

    @Test
    fun aJarIsRefusedWhenTheCompanionBesideItIsForeign() {
        val root = temp("jar-foreign")
        write(root.resolve(JAR), "old-jar")
        write(root.resolve(PROPERTIES), FOREIGN_PROPERTIES)

        val failure = kotlin.runCatching {
            writer().write(
                root = root.okio(),
                files = listOf(jar(root, "new-jar")),
                force = false,
                dryRun = false,
            )
        }.exceptionOrNull()

        assertTrue(failure is ConversionException, "Expected a conversion failure, got $failure")
        assertEquals(JAR_REFUSAL, failure.message)
        assertEquals("old-jar", root.resolve(JAR).readText(), "The refused jar is untouched")
    }

    @Test
    fun aJarIsRefusedWhenTheCompanionBesideItIsGone() {
        val root = temp("jar-orphan")
        write(root.resolve(JAR), "old-jar")

        val failure = kotlin.runCatching {
            writer().write(
                root = root.okio(),
                files = listOf(jar(root, "new-jar")),
                force = false,
                dryRun = false,
            )
        }.exceptionOrNull()

        assertTrue(failure is ConversionException, "Expected a conversion failure, got $failure")
        assertEquals(JAR_REFUSAL, failure.message)
        assertEquals("old-jar", root.resolve(JAR).readText(), "Deleting the only evidence of ownership refuses, not replaces")
    }

    @Test
    fun aRefusedJarIsReplacedWithForce() {
        val root = temp("jar-forced")
        write(root.resolve(JAR), "old-jar")

        writer().write(
            root = root.okio(),
            files = listOf(jar(root, "new-jar")),
            force = true,
            dryRun = false,
        )

        assertEquals("new-jar", root.resolve(JAR).readText(), "--force is the escape hatch out of every refusal row")
    }

    @Test
    fun onlyTheCompanionInTheSameDirectoryVouchesForAJar() {
        val root = temp("jar-sibling")
        write(root.resolve(JAR), "old-jar")
        write(root.resolve("gradle-wrapper.properties"), OUR_PROPERTIES)

        val failure = kotlin.runCatching {
            writer().write(
                root = root.okio(),
                files = listOf(jar(root, "new-jar")),
                force = false,
                dryRun = false,
            )
        }.exceptionOrNull()

        assertTrue(failure is ConversionException, "Expected a conversion failure, got $failure")
        assertEquals(JAR_REFUSAL, failure.message)
    }

    @Test
    fun everyGeneratedFileIsOneTheWriterWillRecogniseAsItsOwn() {
        val source = temp("marker")
        write(source.resolve("module.yaml"), "product: jvm/lib\n")
        val files = Converter(FileSystem.SYSTEM).generateFiles(source.okio()).files

        writer().write(root = source.okio(), files = files, force = false, dryRun = false)
        val rewritten = writer().write(
            root = source.okio(),
            files = files.map(::withChangedContent),
            force = false,
            dryRun = false,
        )

        assertEquals(files.map { notation(it.path.relativeTo(source.okio())) }, rewritten.map(::notation))
    }

    private fun withChangedContent(file: GeneratedFile): GeneratedFile = GeneratedFile(
        path = file.path,
        content = when (val content = file.content) {
            is FileContent.Text -> FileContent.Text(content.value + "\n")
            is FileContent.Binary -> content.copy(bytes = content.bytes.substring(0, content.bytes.size - 1))
        },
    )

    private fun writer() = FileWriter(FileSystem.SYSTEM)

    private fun notation(path: OkioPath) = path.segments.joinToString("/")

    private fun generated(root: Path, relative: String, content: String) = GeneratedFile(
        path = relative.split('/').fold(root.okio()) { path, segment -> path / segment },
        content = FileContent.Text(content),
    )

    private fun jar(root: Path, content: String) = GeneratedFile(
        path = JAR.split('/').fold(root.okio()) { path, segment -> path / segment },
        content = FileContent.Binary(content.encodeUtf8(), ownershipFollows = "gradle-wrapper.properties"),
    )

    private fun temp(name: String): Path =
        Files.createTempDirectory("ktc-to-gradle-writer-").resolve(name).also(Path::createDirectories)

    private fun Path.okio() = toString().toPath()

    private fun write(path: Path, content: String) {
        path.parent.createDirectories()
        path.writeText(content)
    }

    private companion object {
        const val JAR = "gradle/wrapper/gradle-wrapper.jar"
        const val PROPERTIES = "gradle/wrapper/gradle-wrapper.properties"
        const val OUR_PROPERTIES = "# Generated by ktc-to-gradle. Safe to regenerate.\ndistributionPath=wrapper/dists\n"
        const val FOREIGN_PROPERTIES = "distributionPath=wrapper/dists\n"
        const val JAR_REFUSAL =
            "Refusing to overwrite existing files: gradle/wrapper/gradle-wrapper.jar. " +
                "Re-run with --force after reviewing them."
    }
}
