// Generated by ktc-to-gradle 0.12.0-2. Safe to regenerate.
pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = "internal"
            url = uri("https://repo.example/internal")
        }
        gradlePluginPortal()
    }
}

rootProject.name = "custom-repositories"
